### ISSUE TITLE
Core Dumped when running invoke()

### ISSUE THREAD

**Issue by anisiomqs** [rehmanzafar/ssd-resnet-to-tflite#1]
Hello.

Thanks for these instructions. I followed them thoroughly and it all went well. However, when I try to run `interpreter.invoke()` I'm getting `Aborted (core dumped)`. I'm using a Coral USB accelerator, and the problem occurs both plugging it to a macbook and to a raspberry pi. 

Output of the first few lines from the backtrace of `gdb -ex r --args python3 test.py`:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000007fb7e888b4 in __GI_abort () at abort.c:79
#2  0x0000007fb62319a0 in void tflite::reference_ops::BroadcastMul4DSlow<float>(tflite::ArithmeticParams const&, tflite::RuntimeShape const&, float const*, tflite::RuntimeShape const&, float const*, tflite::RuntimeShape const&, float*) ()
   from /home/tooq/.local/lib/python3.6/site-packages/tflite_runtime/_interpreter_wrapper.so
#3  0x0000007fb6234408 in void tflite::ops::builtin::mul::EvalMul<(tflite::ops::builtin::mul::KernelType)2>(TfLiteContext*, TfLiteNode*, TfLiteMulParams*, tflite::ops::builtin::mul::OpData const*, TfLiteTensor const*, TfLiteTensor const*, TfLiteTensor*) ()
   from /home/tooq/.local/lib/python3.6/site-packages/tflite_runtime/_interpreter_wrapper.so
#4  0x0000007fb6241e90 in TfLiteStatus tflite::ops::builtin::mul::Eval<(tflite::ops::builtin::mul::KernelType)2>(TfLiteContext*, TfLiteNode*) ()
   from /home/tooq/.local/lib/python3.6/site-packages/tflite_runtime/_interpreter_wrapper.so
#5  0x0000007fb60ef418 in tflite::Subgraph::Invoke() ()
```

Can you help? 

Thanks in advance.

**Comment by rehmanzafar** [comment]
Please open your issue at https://github.com/tensorflow/tensorflow/issues/
